
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/config-repo

#app:
#  name: Mins app
#  description: Welcome to ${app.name}
#
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"